# Generated by Django 2.1.5 on 2019-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190326_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitycamera',
            name='identifier',
            field=models.CharField(default='deff', max_length=25),
        ),
        migrations.AlterField(
            model_name='securitycamera',
            name='name',
            field=models.CharField(default='def', max_length=25),
        ),
    ]
