# Generated by Django 2.1.5 on 2019-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190326_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitycamera',
            name='identifier',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
