# Generated by Django 2.1.5 on 2019-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190326_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='securitycamera',
            name='identifier',
            field=models.CharField(default='default', max_length=25),
        ),
        migrations.AlterField(
            model_name='securitycamera',
            name='name',
            field=models.CharField(default='default name', max_length=25),
        ),
    ]
