# Generated by Django 2.1.5 on 2019-03-26 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_auto_20190326_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitycamera',
            name='owner',
        ),
        migrations.AddField(
            model_name='securitycamera',
            name='owners',
            field=models.ManyToManyField(default=1, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
